@echo off
rem Rewrites art.js with every PNG in this folder, so the game loads them.
cd /d "%~dp0"
(
echo // Auto-generated by update-art-list.bat - lists the art files present in this folder.
echo // Set ART_PROBE_ALL = true to try every file named in js/sprites.js instead.
echo var ART_PROBE_ALL = false;
echo var ART_FILES = [
for %%f in (*.png) do echo   "%%f",
echo ];
) > art.js
echo art.js updated:
type art.js
pause
